import { GalleryHorizontalEnd, User, Users } from "lucide-react";
import { AccountType } from "./accountType";

export const accountTypes: AccountType[] = [
    {
        id: 1,
        name: "Current Account",
        category: "Individual",
        code: "101",
        icon: User,
        requirements: [
            "BVN (Bank Verification Number)",
            "NIN (National Identification Number)",
            "One (1) clear passport photograph",
            "Valid means of identification (Driver’s License, International Passport, National Identity Card, or Voter’s Card)",
            "Public utility bill dated within the last three (3) months",
            "Two (2) independent and satisfactory account references",
        ],
        benefits: [
            "Suitable for professionals and business owners",
            "Debit card for seamless transactions",
            "Email & SMS transaction alerts",
            "Access to Internet Banking & Mobile Banking",
            "Enhanced transaction limits",
            "Reliable banking for daily business operations",
        ],
    },
    {
        id: 2,
        name: "Savings Account",
        category: "Individual",
        code: "005",
        icon: User,
        requirements: [
            "BVN (Bank Verification Number)",
            "NIN (National Identification Number)",
            "One (1) clear passport photograph",
            "Valid means of identification (Driver's License, International Passport, National Identity Card, or Voter's Card)",
            "Public utility bill dated within the last three (3) months",
        ],
        benefits: [
            "Zero account opening balance",
            "Earn competitive monthly interest (per annum)",
            "Email & SMS transaction alerts",
            "Debit Card for seamless transactions",
            "24/7 access via Internet Banking & Mobile App",
            "Secure and convenient digital banking experience",
            "Fast account activation with minimal documentation",
        ]
    },
    {
        id: 3,
        name: "Corporate Account",
        category: "Corporate",
        code: "101",
        icon: Users,
        requirements: [
            "Valid means of identification for each Director and Signatory",
            "BVN & NIN for each Director and Signatory",
            "One (1) clear passport photograph per Director/Signatory",
            "Public utility bill dated within the last three (3) months",
            "Account References",
        ],
        benefits: [
            "Designed for registered businesses and corporate entities",
            "Multiple signatories & mandate support",
            "Secure Debit Card issuance (where applicable)",
            "Email & SMS transaction alerts",
            "24/7 access to Corporate Internet Banking",
            "Role-based access for account users",
            "Enhanced transaction limits",
            "Reliable banking for business operations",
            "Secure and compliant account opening process",
        ],
    },
    {
        id: 4,
        name: "POS Merchant",
        category: "Merchant",
        code: null,
        icon: GalleryHorizontalEnd,
        requirements: [
            "One passport photograph of each signatory",
            "Valid ID for each signatory",
            "Copy of a utility bill issued within the last three months",
            "Two Reference forms",
            "CAC certificate / TIN / Board resolution",
        ],
        benefits: [
            "Designed for POS merchants and service providers",
            "Dedicated account for POS settlements",
            "Fast and secure transaction processing",
            "Daily settlement into merchant account",
            "Email & SMS transaction alerts",
            "Access to Internet Banking",
            "Improved transaction monitoring & reporting",
            "Secure Debit Card issuance (where applicable)",
        ],
    },
];