export const accountUpdateMapper = (payload: any, accountNumber: string) => ({
        account_number: accountNumber,
        mother_maiden_name: payload.mothersMaidenName,
        phone_number: payload.phoneNumber,
        email_address: payload.emailAddress,
        employment_status: payload.employmentStatus,
        employer: payload.employer,
        account_officer: payload.accountOfficer,
        marital_status: payload.maritalStatus,
        house_number: payload.houseNumber,
        street: payload.street,
        city: payload.city,
        state: payload.state,
        origin: payload.origin,
        lga: payload.lga,
        next_of_kin_name: payload.nextOfKinName,
        next_of_kin_address: payload.nextOfKinAddress,
        next_of_kin_phone_number: payload.nextOfKinPhone,
        next_of_kin_relationship: payload.nextOfKinRelationship,
});
