export interface BankOption {
  label: string;
  value: string;
}

export const BANKS: BankOption[] = [
  { label: "78 FINANCE COMPANY LIMITED", value: "78 FINANCE COMPANY LIMITED" },
  { label: "9JAPAY MICROFINANCE BANK", value: "9JAPAY MICROFINANCE BANK" },
  { label: "9 payment service Bank", value: "9 payment service Bank" },
  { label: "AAA FINANCE", value: "AAA FINANCE" },
  { label: "ABBEY MORTGAGE BANK", value: "ABBEY MORTGAGE BANK" },
  { label: "AB MICROFINANCE BANK", value: "AB MICROFINANCE BANK" },
  { label: "ABOVE ONLY MICROFINANCE BANK", value: "ABOVE ONLY MICROFINANCE BANK" },
  { label: "ABSU MICROFINANCE BANK", value: "ABSU MICROFINANCE BANK" },
  { label: "ABUCOOP MICROFINANCE BANK", value: "ABUCOOP MICROFINANCE BANK" },
  { label: "ABULESORO MICROFINANCE BANK", value: "ABULESORO MICROFINANCE BANK" },
  { label: "ABU MICROFINANCE BANK", value: "ABU MICROFINANCE BANK" },
  { label: "ACCESS BANK", value: "ACCESS BANK" },
  { label: "ACCESSMONEY", value: "ACCESSMONEY" },
  { label: "Access Yello and Beta", value: "Access Yello and Beta" },
  { label: "ACCION MFB", value: "ACCION MFB" },
  { label: "ADA MFB", value: "ADA MFB" },
  { label: "ADDOSSER MFBB", value: "ADDOSSER MFBB" },
  { label: "ADEYEMI COLLEGE STAFF MICROFINANCE BANK", value: "ADEYEMI COLLEGE STAFF MICROFINANCE BANK" },
  { label: "ADVANS LA FAYETTE MFB", value: "ADVANS LA FAYETTE MFB" },
  { label: "Afekhafe MFB", value: "Afekhafe MFB" },
  { label: "AFEMAI MICROFINANCE BANK", value: "AFEMAI MICROFINANCE BANK" },
  { label: "AG MORTGAGE BANK PLC", value: "AG MORTGAGE BANK PLC" },
  { label: "AGOSASA MICROFINANCE BANK", value: "AGOSASA MICROFINANCE BANK" },
  { label: "Akpo Microfinance Bank", value: "Akpo Microfinance Bank" },
  { label: "AKUCHUKWU MICROFINANCE BANK", value: "AKUCHUKWU MICROFINANCE BANK" },
  { label: "Aku MFB", value: "Aku MFB" },
  { label: "Akwa savings & Loans Limited", value: "Akwa savings & Loans Limited" },
  { label: "AL-BARKAH MFB", value: "AL-BARKAH MFB" },
  { label: "ALEKUN MICROFINANCE BANK", value: "ALEKUN MICROFINANCE BANK" },
  { label: "ALERT MFB", value: "ALERT MFB" },
  { label: "ALHAYAT MFB", value: "ALHAYAT MFB" },
  { label: "ALLWORKERS MFB", value: "ALLWORKERS MFB" },
  { label: "ALLY MICROFINANCE BANK", value: "ALLY MICROFINANCE BANK" },
  { label: "ALPHAKAPITAL MFB", value: "ALPHAKAPITAL MFB" },
  { label: "ALTERNATIVE BANK LIMITED", value: "ALTERNATIVE BANK LIMITED" },
  { label: "ALVANA MICROFINANCE BANK", value: "ALVANA MICROFINANCE BANK" },
  { label: "Amac Microfinance Bank", value: "Amac Microfinance Bank" },
  { label: "AMJU MFB", value: "AMJU MFB" },
  { label: "AMML MFB", value: "AMML MFB" },
  { label: "AMOYE MICROFINANCE BANK", value: "AMOYE MICROFINANCE BANK" },
  { label: "AMUCHA MICROFINANCE BANK", value: "AMUCHA MICROFINANCE BANK" },
  { label: "ANCHORAGE MICROFINANCE BANK", value: "ANCHORAGE MICROFINANCE BANK" },
  { label: "APEKS MICROFINANCE BANK", value: "APEKS MICROFINANCE BANK" },
  { label: "APPLE  MICROFINANCE BANK", value: "APPLE  MICROFINANCE BANK" },
  { label: "ARAMOKO MICROFINANCE BANK", value: "ARAMOKO MICROFINANCE BANK" },
  { label: "Arise MFB", value: "Arise MFB" },
  { label: "ASOSAVINGS", value: "ASOSAVINGS" },
  { label: "ASPIRE MICROFINANCE BANK", value: "ASPIRE MICROFINANCE BANK" },
  { label: "Assets Matrix MFB", value: "Assets Matrix MFB" },
  { label: "ASSETS MICROFINANCE BANK", value: "ASSETS MICROFINANCE BANK" },
  { label: "ASTRAPOLARIS MFB", value: "ASTRAPOLARIS MFB" },
  { label: "ATBU MICROFINANCE BANK", value: "ATBU MICROFINANCE BANK" },
  { label: "AUCHI MICROFINANCE BANK", value: "AUCHI MICROFINANCE BANK" },
  { label: "AVE MARIA MICROFINANCE BANK LTD", value: "AVE MARIA MICROFINANCE BANK LTD" },
  { label: "AVUENEGBE MICROFINANCE BANK", value: "AVUENEGBE MICROFINANCE BANK" },
  { label: "AWACASH MICROFINANCE BANK", value: "AWACASH MICROFINANCE BANK" },
  { label: "AWESOME MICROFINANCE BANK", value: "AWESOME MICROFINANCE BANK" },
  { label: "AZTEC MICROFINANCE BANK", value: "AZTEC MICROFINANCE BANK" },
  { label: "BABURA MICROFINANCE BANK", value: "BABURA MICROFINANCE BANK" },
  { label: "BAINES CREDIT MFB", value: "BAINES CREDIT MFB" },
  { label: "Balera Microfinance Bank", value: "Balera Microfinance Bank" },
  { label: "Balogun Fulani MFB", value: "Balogun Fulani MFB" },
  { label: "BALOGUN GAMBARI MFB", value: "BALOGUN GAMBARI MFB" },
  { label: "BAM MICROFINANCE BANK", value: "BAM MICROFINANCE BANK" },
  { label: "BANC CORP MICROFINANCE BANK LTD", value: "BANC CORP MICROFINANCE BANK LTD" },
  { label: "BANEX MICROFINANCE BANK", value: "BANEX MICROFINANCE BANK" },
  { label: "Bankly Microfinance Bank", value: "Bankly Microfinance Bank" },
  { label: "BAOBAB MICROFINANCE BANK", value: "BAOBAB MICROFINANCE BANK" },
  { label: "BAYERO MICROFINANCE BANK", value: "BAYERO MICROFINANCE BANK" },
  { label: "BC KASH MFB", value: "BC KASH MFB" },
  { label: "BELLBANK Microfinance Bank", value: "BELLBANK Microfinance Bank" },
  { label: "BENYSTA MICROFINANCE BANK", value: "BENYSTA MICROFINANCE BANK" },
  { label: "Beststar MFB", value: "Beststar MFB" },
  { label: "BETHEL MICROFINANCE BANK", value: "BETHEL MICROFINANCE BANK" },
  { label: "BIPC MICROFINANCE BANK", value: "BIPC MICROFINANCE BANK" },
  { label: "BishopGate Microfinance Bank", value: "BishopGate Microfinance Bank" },
  { label: "BLUEPRINT INVESTMENTS MFB", value: "BLUEPRINT INVESTMENTS MFB" },
  { label: "BLUEWHALES MICROFINANCE BANK", value: "BLUEWHALES MICROFINANCE BANK" },
  { label: "Boctrust Microfinance Bank", value: "Boctrust Microfinance Bank" },
  { label: "BOI MICROFINANCE BANK", value: "BOI MICROFINANCE BANK" },
  { label: "BOJI BOJI MICROFINANCE BANK", value: "BOJI BOJI MICROFINANCE BANK" },
  { label: "BONGHE MICROFINANCE BANK", value: "BONGHE MICROFINANCE BANK" },
  { label: "Borgu MFB", value: "Borgu MFB" },
  { label: "Borno Renaissance Microfinance bank", value: "Borno Renaissance Microfinance bank" },
  { label: "Boromu Microfinance bank", value: "Boromu Microfinance bank" },
  { label: "BORSTAL MICROFINANCE BANK", value: "BORSTAL MICROFINANCE BANK" },
  { label: "Bosak MFB", value: "Bosak MFB" },
  { label: "Bowen MFB", value: "Bowen MFB" },
  { label: "Branch International Financial Services", value: "Branch International Financial Services" },
  { label: "BRENT Mortgage Bank", value: "BRENT Mortgage Bank" },
  { label: "BRETHREN MICROFINANCE BANK", value: "BRETHREN MICROFINANCE BANK" },
  { label: "Bridgeway Microfinance Bank", value: "Bridgeway Microfinance Bank" },
  { label: "Brightway Microfinance Bank", value: "Brightway Microfinance Bank" },
  { label: "BRIYTH-COVENANT MICROFINANCE BANK", value: "BRIYTH-COVENANT MICROFINANCE BANK" },
  { label: "BROADVIEW MICROFINANCE BANK LTD", value: "BROADVIEW MICROFINANCE BANK LTD" },
  { label: "BUBAYERO MICORFINANCE BANK", value: "BUBAYERO MICORFINANCE BANK" },
  { label: "BUNDI MICROFINANCE BANK", value: "BUNDI MICROFINANCE BANK" },
  { label: "BUNKURE MICROFINANCE BANK", value: "BUNKURE MICROFINANCE BANK" },
  { label: "Business Support Microfinance Bank", value: "Business Support Microfinance Bank" },
  { label: "BUYPOWER MICROFINANCE BANK", value: "BUYPOWER MICROFINANCE BANK" },
  { label: "Calabar Microfinance Bank", value: "Calabar Microfinance Bank" },
  { label: "CANAAN MICROFINANCE BANK", value: "CANAAN MICROFINANCE BANK" },
  { label: "CAPITALMETRIQ SWIFT MFB", value: "CAPITALMETRIQ SWIFT MFB" },
  { label: "CAPSTONE MICROFINANCE BANK", value: "CAPSTONE MICROFINANCE BANK" },
  { label: "CARBON MICROFINANCE BANK", value: "CARBON MICROFINANCE BANK" },
  { label: "CARETAKER MICROFINANCE BANK", value: "CARETAKER MICROFINANCE BANK" },
  { label: "CASHBRIDGE MICROFINANCE BANK", value: "CASHBRIDGE MICROFINANCE BANK" },
  { label: "CASHCONNECT   MICROFINANCE BANK", value: "CASHCONNECT   MICROFINANCE BANK" },
  { label: "CASHRITE MICROFINANCE BANK", value: "CASHRITE MICROFINANCE BANK" },
  { label: "CATLAND MFB", value: "CATLAND MFB" },
  { label: "Cedar Microfinance Bank", value: "Cedar Microfinance Bank" },
  { label: "CELLULANT", value: "CELLULANT" },
  { label: "CEMCS MFB", value: "CEMCS MFB" },
  { label: "Central Bank of Nigeria", value: "Central Bank of Nigeria" },
  { label: "ChamsMobile", value: "ChamsMobile" },
  { label: "Chanelle Bank", value: "Chanelle Bank" },
  { label: "Chase Microfinance bank", value: "Chase Microfinance bank" },
  { label: "CHERISH MICROFINANCE BANK", value: "CHERISH MICROFINANCE BANK" },
  { label: "Chibueze Microfinance Bank", value: "Chibueze Microfinance Bank" },
  { label: "CHIKUM MICROFINANCE BANK", value: "CHIKUM MICROFINANCE BANK" },
  { label: "CHUKWUNENYE  MICROFINANCE BANK", value: "CHUKWUNENYE  MICROFINANCE BANK" },
  { label: "CITI BANK", value: "CITI BANK" },
  { label: "Citizen Trust MICROFINANCE BANK", value: "Citizen Trust MICROFINANCE BANK" },
  { label: "CIT MICROFINANCE BANK", value: "CIT MICROFINANCE BANK" },
  { label: "CITYCODE MORTGAGE BANK", value: "CITYCODE MORTGAGE BANK" },
  { label: "Clover Leaf Microfinance Bank", value: "Clover Leaf Microfinance Bank" },
  { label: "COALCAMP MICROFINANCE  BANK", value: "COALCAMP MICROFINANCE  BANK" },
  { label: "COASTLINE MICROFINANCE BANK", value: "COASTLINE MICROFINANCE BANK" },
  { label: "CONFIDENCE MICROFINANCE BANK", value: "CONFIDENCE MICROFINANCE BANK" },
  { label: "CONSISTENT TRUST MFB", value: "CONSISTENT TRUST MFB" },
  { label: "CONSUMER  MFB", value: "CONSUMER  MFB" },
  { label: "CONTEC GLOBAL", value: "CONTEC GLOBAL" },
  { label: "COOP Mortgage Bank", value: "COOP Mortgage Bank" },
  { label: "CORESTEP MFB", value: "CORESTEP MFB" },
  { label: "CORONATION", value: "CORONATION" },
  { label: "COUNTY FINANCE LIMITED", value: "COUNTY FINANCE LIMITED" },
  { label: "COVENANT MFB", value: "COVENANT MFB" },
  { label: "CREDIT AFRIQUE MFB", value: "CREDIT AFRIQUE MFB" },
  { label: "Creditville MFB", value: "Creditville MFB" },
  { label: "CRESCENT MICROFINANCE BANK", value: "CRESCENT MICROFINANCE BANK" },
  { label: "CROSSRIVER MICROFINANCE BANK", value: "CROSSRIVER MICROFINANCE BANK" },
  { label: "CROWDFORCE MICROFINANCE BANK", value: "CROWDFORCE MICROFINANCE BANK" },
  { label: "CRUST MICROFINANCE BANK", value: "CRUST MICROFINANCE BANK" },
  { label: "CRUTECH MICROFINANCE BANK", value: "CRUTECH MICROFINANCE BANK" },
  { label: "CSD MICROFINANCE BANK LIMITED", value: "CSD MICROFINANCE BANK LIMITED" },
  { label: "DAL MICROFINANCE BANK", value: "DAL MICROFINANCE BANK" },
  { label: "DAVENPORT MICROFINANCE BANK", value: "DAVENPORT MICROFINANCE BANK" },
  { label: "Davodani  Microfinance Bank", value: "Davodani  Microfinance Bank" },
  { label: "DAYLIGHT MICROFINANCE BANK", value: "DAYLIGHT MICROFINANCE BANK" },
  { label: "Delta Trust Mortgage Bank", value: "Delta Trust Mortgage Bank" },
  { label: "Dignity Finance", value: "Dignity Finance" },
  { label: "DIOBU MICROFINANCE BANK", value: "DIOBU MICROFINANCE BANK" },
  { label: "DOT MFB", value: "DOT MFB" },
  { label: "EAGLE FLIGHT MFB", value: "EAGLE FLIGHT MFB" },
  { label: "EARNWELL MICROFINANCE BANK", value: "EARNWELL MICROFINANCE BANK" },
  { label: "Eartholeum", value: "Eartholeum" },
  { label: "E-BARCS MFB", value: "E-BARCS MFB" },
  { label: "EBSU MFB", value: "EBSU MFB" },
  { label: "ECOBANK BANK", value: "ECOBANK BANK" },
  { label: "ECOBANK XPRESS ACCOUNT", value: "ECOBANK XPRESS ACCOUNT" },
  { label: "EcoMobile", value: "EcoMobile" },
  { label: "EdFin Microfinance Bank", value: "EdFin Microfinance Bank" },
  { label: "E-FINANCE", value: "E-FINANCE" },
  { label: "EGWAFIN MICROFINANCE BANK", value: "EGWAFIN MICROFINANCE BANK" },
  { label: "EJINDU MFB", value: "EJINDU MFB" },
  { label: "EKIMOGUN MFB", value: "EKIMOGUN MFB" },
  { label: "Ekondo MFB", value: "Ekondo MFB" },
  { label: "EK-Reliable Microfinance Bank", value: "EK-Reliable Microfinance Bank" },
  { label: "EMERALDS MFB", value: "EMERALDS MFB" },
  { label: "EMPIRETRUST MICROFINANCE BANK", value: "EMPIRETRUST MICROFINANCE BANK" },
  { label: "eNaira", value: "eNaira" },
  { label: "Enco Finance", value: "Enco Finance" },
  { label: "Enterprise Bank", value: "Enterprise Bank" },
  { label: "ENTITY MICROFINANCE BANK", value: "ENTITY MICROFINANCE BANK" },
  { label: "ESAN MFB", value: "ESAN MFB" },
  { label: "ESO-E MICROFINANCE BANK", value: "ESO-E MICROFINANCE BANK" },
  { label: "ETRANZACT", value: "ETRANZACT" },
  { label: "EVANGEL MFB", value: "EVANGEL MFB" },
  { label: "EVERGREEN MICROFINANCE BANK", value: "EVERGREEN MICROFINANCE BANK" },
  { label: "EWT Microfinance Bank", value: "EWT Microfinance Bank" },
  { label: "EXCELLENT MICROFINANCE BANK", value: "EXCELLENT MICROFINANCE BANK" },
  { label: "EXCEL MICROFINANCE BANK", value: "EXCEL MICROFINANCE BANK" },
  { label: "EYOWO MICROFINANCE BANK", value: "EYOWO MICROFINANCE BANK" },
  { label: "FAIRMONEY MICROFINANCE BANK", value: "FAIRMONEY MICROFINANCE BANK" },
  { label: "FAME MICROFINANCE BANK", value: "FAME MICROFINANCE BANK" },
  { label: "FAST CREDIT", value: "FAST CREDIT" },
  { label: "FAST Microfinance Bank", value: "FAST Microfinance Bank" },
  { label: "FBNQUEST MERCHANT BANK", value: "FBNQUEST MERCHANT BANK" },
  { label: "FCMB", value: "FCMB" },
  { label: "FCMB MFB", value: "FCMB MFB" },
  { label: "FCMB MOBILE", value: "FCMB MOBILE" },
  { label: "FCT MFB", value: "FCT MFB" },
  { label: "FEDERALPOLY NASARAWAMFB", value: "FEDERALPOLY NASARAWAMFB" },
  { label: "Federal Polytechnic Nekede Microfinance Bank", value: "Federal Polytechnic Nekede Microfinance Bank" },
  { label: "FEDERAL UNIVERSITY DUTSE  MICROFINANCE BANK", value: "FEDERAL UNIVERSITY DUTSE  MICROFINANCE BANK" },
  { label: "FETS", value: "FETS" },
  { label: "Fewchore Finance Company Limited", value: "Fewchore Finance Company Limited" },
  { label: "FFS MICROFINANCE BANK", value: "FFS MICROFINANCE BANK" },
  { label: "FHA MORTGAGE BANK LTD", value: "FHA MORTGAGE BANK LTD" },
  { label: "FIDELITY BANK", value: "FIDELITY BANK" },
  { label: "FIDELITY MOBILE", value: "FIDELITY MOBILE" },
  { label: "FidFund MFB", value: "FidFund MFB" },
  { label: "FIMS MICROFINANCE BANK", value: "FIMS MICROFINANCE BANK" },
  { label: "FinaTrust Microfinance Bank", value: "FinaTrust Microfinance Bank" },
  { label: "Finca Microfinance Bank", value: "Finca Microfinance Bank" },
  { label: "Finex MFB", value: "Finex MFB" },
  { label: "Firmus MICROFINANCE BANK", value: "Firmus MICROFINANCE BANK" },
  { label: "FIRST BANK OF NIGERIA", value: "FIRST BANK OF NIGERIA" },
  { label: "FIRST GENERATION MORTGAGE BANK", value: "FIRST GENERATION MORTGAGE BANK" },
  { label: "First Heritage MICROFINANCE BANK", value: "First Heritage MICROFINANCE BANK" },
  { label: "FIRSTMIDAS MICROFINANCE BANK LTD", value: "FIRSTMIDAS MICROFINANCE BANK LTD" },
  { label: "FIRSTMONIE WALLET", value: "FIRSTMONIE WALLET" },
  { label: "FIRST MULTIPLE MFB", value: "FIRST MULTIPLE MFB" },
  { label: "FIRST OPTION MFB", value: "FIRST OPTION MFB" },
  { label: "FIRST ROYAL MICROFINANCE BANK", value: "FIRST ROYAL MICROFINANCE BANK" },
  { label: "FIRSTTRUST MORGAGES LIMITED", value: "FIRSTTRUST MORGAGES LIMITED" },
  { label: "Flourish MFB", value: "Flourish MFB" },
  { label: "FORESIGHT MICROFINANCE BANK", value: "FORESIGHT MICROFINANCE BANK" },
  { label: "Fortis Microfinance Bank", value: "Fortis Microfinance Bank" },
  { label: "FORTISMOBILE", value: "FORTISMOBILE" },
  { label: "FORTRESS MICROFINANCE BANK", value: "FORTRESS MICROFINANCE BANK" },
  { label: "FSDH", value: "FSDH" },
  { label: "FULL RANGE MFB", value: "FULL RANGE MFB" },
  { label: "FUNDQUEST FINANCIAL SERVICES LMT", value: "FUNDQUEST FINANCIAL SERVICES LMT" },
  { label: "FUTMINNA MICROFINANCE BANK", value: "FUTMINNA MICROFINANCE BANK" },
  { label: "FUTO MFB", value: "FUTO MFB" },
  { label: "GABASAWA MICROFINANCE BANK", value: "GABASAWA MICROFINANCE BANK" },
  { label: "Gabsyn MFB", value: "Gabsyn MFB" },
  { label: "GARKI MICROFINANCE BANK", value: "GARKI MICROFINANCE BANK" },
  { label: "Garun Mallam MFB", value: "Garun Mallam MFB" },
  { label: "GASHUA MICROFINANCE BANK", value: "GASHUA MICROFINANCE BANK" },
  { label: "Gateway Mortgage", value: "Gateway Mortgage" },
  { label: "GBEDE Microfinance Bank", value: "GBEDE Microfinance Bank" },
  { label: "Giant Stride MFB", value: "Giant Stride MFB" },
  { label: "GIDAUNIYAR ALHERI MICROFINANCE BANK", value: "GIDAUNIYAR ALHERI MICROFINANCE BANK" },
  { label: "GiGinya Microfinance Bank", value: "GiGinya Microfinance Bank" },
  { label: "Girei MFB", value: "Girei MFB" },
  { label: "GIWA MICROFINANCE BANK", value: "GIWA MICROFINANCE BANK" },
  { label: "GLOBAL INITIATIVE MICROFINANCE BANK", value: "GLOBAL INITIATIVE MICROFINANCE BANK" },
  { label: "GLOBUS BANK", value: "GLOBUS BANK" },
  { label: "GLORY MFB", value: "GLORY MFB" },
  { label: "GMB Microfinance Bank", value: "GMB Microfinance Bank" },
  { label: "GOLDMAN MICROFINANCE BANK LTD", value: "GOLDMAN MICROFINANCE BANK LTD" },
  { label: "GOMBE MICROFINANCE BANK LTD", value: "GOMBE MICROFINANCE BANK LTD" },
  { label: "GOMONEY", value: "GOMONEY" },
  { label: "Good Neighbours MFB", value: "Good Neighbours MFB" },
  { label: "GOSIFECHUKWU MFB", value: "GOSIFECHUKWU MFB" },
  { label: "GOWANS MFB", value: "GOWANS MFB" },
  { label: "GRANT MFB", value: "GRANT MFB" },
  { label: "Greenacres MFB", value: "Greenacres MFB" },
  { label: "GREENBANK MFB", value: "GREENBANK MFB" },
  { label: "Green Energy Microfinance Bank", value: "Green Energy Microfinance Bank" },
  { label: "GREENVILLE MICROFINANCE BANK", value: "GREENVILLE MICROFINANCE BANK" },
  { label: "GREENWICH MERCHANT BANK", value: "GREENWICH MERCHANT BANK" },
  { label: "GROOMING MICROFINANCE BANK", value: "GROOMING MICROFINANCE BANK" },
  { label: "GTBANK PLC", value: "GTBANK PLC" },
  { label: "GTI  Microfinance Bank", value: "GTI  Microfinance Bank" },
  { label: "GTMobile", value: "GTMobile" },
  { label: "GWONG MICROFINANCE BANK", value: "GWONG MICROFINANCE BANK" },
  { label: "HACKMAN MICROFINANCE BANK", value: "HACKMAN MICROFINANCE BANK" },
  { label: "HAGGAI MORTGAGE BANK", value: "HAGGAI MORTGAGE BANK" },
  { label: "HALALCREDIT MICROFINANCE BANK", value: "HALALCREDIT MICROFINANCE BANK" },
  { label: "HALO MICROFINANCE BANk", value: "HALO MICROFINANCE BANk" },
  { label: "HASAL MFB", value: "HASAL MFB" },
  { label: "Headway MFB", value: "Headway MFB" },
  { label: "Hedonmark", value: "Hedonmark" },
  { label: "HERITAGE", value: "HERITAGE" },
  { label: "HIGHLAND MICROFINANCE BANK", value: "HIGHLAND MICROFINANCE BANK" },
  { label: "HOMEBASE MORTGAGE BANK", value: "HOMEBASE MORTGAGE BANK" },
  { label: "HopePSB", value: "HopePSB" },
  { label: "IBA MFB", value: "IBA MFB" },
  { label: "IBETO MICROFINANCE BANK", value: "IBETO MICROFINANCE BANK" },
  { label: "IBILE MICROFINANCE BANK", value: "IBILE MICROFINANCE BANK" },
  { label: "IBOLO MICROFINANCE BANK", value: "IBOLO MICROFINANCE BANK" },
  { label: "IBOMA FADAMA MICROFINANCE BANK", value: "IBOMA FADAMA MICROFINANCE BANK" },
  { label: "IBU-AJE MICROFINANCE BANK", value: "IBU-AJE MICROFINANCE BANK" },
  { label: "IC-GLOBAL MFB", value: "IC-GLOBAL MFB" },
  { label: "Ijebu-Ife Microfinance Bank", value: "Ijebu-Ife Microfinance Bank" },
  { label: "IKENNE MFB", value: "IKENNE MFB" },
  { label: "IKIRE MFB", value: "IKIRE MFB" },
  { label: "IKOYI ILE MICROFINANCE BANK", value: "IKOYI ILE MICROFINANCE BANK" },
  { label: "IKOYI-OSUN MICROFINANCE BANK", value: "IKOYI-OSUN MICROFINANCE BANK" },
  { label: "ILARO POLY MICROFINANCE BANK LTD", value: "ILARO POLY MICROFINANCE BANK LTD" },
  { label: "ILASAN MICROFINANCE BANK", value: "ILASAN MICROFINANCE BANK" },
  { label: "ILORA MICROFINANCE  BANK", value: "ILORA MICROFINANCE  BANK" },
  { label: "ILORIN MICROFINANCE BANK", value: "ILORIN MICROFINANCE BANK" },
  { label: "IMO MICROFINANCE BANK", value: "IMO MICROFINANCE BANK" },
  { label: "Imowo Microfinance Bank", value: "Imowo Microfinance Bank" },
  { label: "Imperial Homes", value: "Imperial Homes" },
  { label: "IMSU MICROFINANCE BANK", value: "IMSU MICROFINANCE BANK" },
  { label: "INFINITY MFB", value: "INFINITY MFB" },
  { label: "INFINITY TRUST  MORTGAGE BANK", value: "INFINITY TRUST  MORTGAGE BANK" },
  { label: "INSIGHT MICROFINANCE BANK", value: "INSIGHT MICROFINANCE BANK" },
  { label: "Intellifin", value: "Intellifin" },
  { label: "Interland MFB", value: "Interland MFB" },
  { label: "Interswitch Financial Inclusion Services (IFIS)", value: "Interswitch Financial Inclusion Services (IFIS)" },
  { label: "Iperu MFB", value: "Iperu MFB" },
  { label: "IRL MICROFINANCE BANK", value: "IRL MICROFINANCE BANK" },
  { label: "ISALEOYO MICROFINANCE BANK", value: "ISALEOYO MICROFINANCE BANK" },
  { label: "ISHIE MICROFINANCE BANK", value: "ISHIE MICROFINANCE BANK" },
  { label: "ISLAND MICROFINANCE BANK LTD", value: "ISLAND MICROFINANCE BANK LTD" },
  { label: "Isuofia MFB", value: "Isuofia MFB" },
  { label: "IWADE MICROFINANCE BANK LTD", value: "IWADE MICROFINANCE BANK LTD" },
  { label: "Iwoama Microfinance Bank", value: "Iwoama Microfinance Bank" },
  { label: "IYAMOYE MICROFINANCE BANK LTD", value: "IYAMOYE MICROFINANCE BANK LTD" },
  { label: "IYERU OKIN MICROFINANCE BANK LTD", value: "IYERU OKIN MICROFINANCE BANK LTD" },
  { label: "Iyin Ekiti MFB", value: "Iyin Ekiti MFB" },
  { label: "IZON MICROFINANCE BANK", value: "IZON MICROFINANCE BANK" },
  { label: "JAIZ BANK", value: "JAIZ BANK" },
  { label: "JESSEFIELD Microfinance Bank", value: "JESSEFIELD Microfinance Bank" },
  { label: "JUBILEELIFE", value: "JUBILEELIFE" },
  { label: "KADPOLY MICROFINANCE BANK", value: "KADPOLY MICROFINANCE BANK" },
  { label: "KADUPE MICROFINANCE BANK", value: "KADUPE MICROFINANCE BANK" },
  { label: "Kano Poly MFB", value: "Kano Poly MFB" },
  { label: "KAYI MICROFINANCE BANK", value: "KAYI MICROFINANCE BANK" },
  { label: "KAYVEE MICROFINANCE BANK", value: "KAYVEE MICROFINANCE BANK" },
  { label: "KCMB MFB", value: "KCMB MFB" },
  { label: "KC Microfinance Bank", value: "KC Microfinance Bank" },
  { label: "KENECHUKWU MICROFINANCE BANK", value: "KENECHUKWU MICROFINANCE BANK" },
  { label: "KEYSTONE BANK", value: "KEYSTONE BANK" },
  { label: "KINGDOM COLLEGE MICROFINANCE BANK", value: "KINGDOM COLLEGE MICROFINANCE BANK" },
  { label: "KKU Microfinance Bank", value: "KKU Microfinance Bank" },
  { label: "Kolomoni Microfinance Bank", value: "Kolomoni Microfinance Bank" },
  { label: "KONGAPAY", value: "KONGAPAY" },
  { label: "KONTAGORA MFB", value: "KONTAGORA MFB" },
  { label: "KOPO KOPE MICROFINANCE BANK", value: "KOPO KOPE MICROFINANCE BANK" },
  { label: "KREDI MONEY MICROFINANCE BANK", value: "KREDI MONEY MICROFINANCE BANK" },
  { label: "KUDA MICROFINANCE BANK", value: "KUDA MICROFINANCE BANK" },
  { label: "KWASU MICROFINANCE BANK", value: "KWASU MICROFINANCE BANK" },
  { label: "Landgold  Microfinance Bank", value: "Landgold  Microfinance Bank" },
  { label: "LAPO Microfinance Bank Limited", value: "LAPO Microfinance Bank Limited" },
  { label: "Lavender Microfinance bank", value: "Lavender Microfinance bank" },
  { label: "LBIC MORTGAGE BANK", value: "LBIC MORTGAGE BANK" },
  { label: "LEADCITY MICROFINANCE BANK", value: "LEADCITY MICROFINANCE BANK" },
  { label: "Leadremit Limited", value: "Leadremit Limited" },
  { label: "LEGEND MICROFINANCE BANK", value: "LEGEND MICROFINANCE BANK" },
  { label: "LETSHEGO MICROFINANCE BANK", value: "LETSHEGO MICROFINANCE BANK" },
  { label: "LIFEGATE MICROFINANCE BANK", value: "LIFEGATE MICROFINANCE BANK" },
  { label: "LIGHT MICROFINANCE BANK", value: "LIGHT MICROFINANCE BANK" },
  { label: "LINKS MICROFINANCE BANK", value: "LINKS MICROFINANCE BANK" },
  { label: "LIVINGTRUST MORTGAGE BANK PLC", value: "LIVINGTRUST MORTGAGE BANK PLC" },
  { label: "LOBREM MICROFINANCE BANK", value: "LOBREM MICROFINANCE BANK" },
  { label: "LOTUS BANK", value: "LOTUS BANK" },
  { label: "LOVONUS MICROFINANCE BANK", value: "LOVONUS MICROFINANCE BANK" },
  { label: "Lukefield Finance Company Limited", value: "Lukefield Finance Company Limited" },
  { label: "M36", value: "M36" },
  { label: "Mab Allianz MFB", value: "Mab Allianz MFB" },
  { label: "MABINAS MICROFINANCE BANK", value: "MABINAS MICROFINANCE BANK" },
  { label: "Macrod MFB", value: "Macrod MFB" },
  { label: "MADOBI MICROFINANCE BANK", value: "MADOBI MICROFINANCE BANK" },
  { label: "MAINLAND MICROFINANCE BANK", value: "MAINLAND MICROFINANCE BANK" },
  { label: "MAINSTREET MFB", value: "MAINSTREET MFB" },
  { label: "MALACHY MFB", value: "MALACHY MFB" },
  { label: "MANNY MICROFINANCE BANK", value: "MANNY MICROFINANCE BANK" },
  { label: "Maritime Microfinance Bank", value: "Maritime Microfinance Bank" },
  { label: "MAUTECH MICROFINANCE BANK", value: "MAUTECH MICROFINANCE BANK" },
  { label: "Mayfair  MFB", value: "Mayfair  MFB" },
  { label: "MAYFRESH MORTGAGE BANK", value: "MAYFRESH MORTGAGE BANK" },
  { label: "Medef MFB", value: "Medef MFB" },
  { label: "MEGAPRAISE MICROFINANCE BANK", value: "MEGAPRAISE MICROFINANCE BANK" },
  { label: "MEMPHIS MICROFINANCE  BANK", value: "MEMPHIS MICROFINANCE  BANK" },
  { label: "MERCURY MICROFINANCE BANK", value: "MERCURY MICROFINANCE BANK" },
  { label: "MERIDIAN MFB", value: "MERIDIAN MFB" },
  { label: "MGBIDI MICROFINANCE BANK", value: "MGBIDI MICROFINANCE BANK" },
  { label: "MICHAEL OKPARA UNIAGRIC  MCF BANK", value: "MICHAEL OKPARA UNIAGRIC  MCF BANK" },
  { label: "Microbiz MFB", value: "Microbiz MFB" },
  { label: "MICROVIS MICROFINANCE BANK", value: "MICROVIS MICROFINANCE BANK" },
  { label: "Midland MFB", value: "Midland MFB" },
  { label: "MINJIBIR MICROFINANCE BANK", value: "MINJIBIR MICROFINANCE BANK" },
  { label: "MKOBO MICROFINANCE BANK LTD", value: "MKOBO MICROFINANCE BANK LTD" },
  { label: "Mkudi", value: "Mkudi" },
  { label: "M & M MICROFINANCE BANK", value: "M & M MICROFINANCE BANK" },
  { label: "MOLUSI MICROFINANCE BANK", value: "MOLUSI MICROFINANCE BANK" },
  { label: "MOMO PAYMENT SERVICE BANK", value: "MOMO PAYMENT SERVICE BANK" },
  { label: "MONARCH MICROFINANCE BANK", value: "MONARCH MICROFINANCE BANK" },
  { label: "MoneyBox", value: "MoneyBox" },
  { label: "MONEYMASTER PSB", value: "MONEYMASTER PSB" },
  { label: "MONEYTRUST MFB", value: "MONEYTRUST MFB" },
  { label: "MONIEPOINT MICROFINANCE BANK", value: "MONIEPOINT MICROFINANCE BANK" },
  { label: "MOYOFADE MICROFINANCE BANK", value: "MOYOFADE MICROFINANCE BANK" },
  { label: "Mozfin Microfinance Bank", value: "Mozfin Microfinance Bank" },
  { label: "MUTUAL ALLIANCE MORTGAGE BANK", value: "MUTUAL ALLIANCE MORTGAGE BANK" },
  { label: "MUTUAL BENEFITS MFB", value: "MUTUAL BENEFITS MFB" },
  { label: "MUTUAL TRUST MICROFINANCE BANK", value: "MUTUAL TRUST MICROFINANCE BANK" },
  { label: "Nargata MFB", value: "Nargata MFB" },
  { label: "Nasarawa Microfinance bank", value: "Nasarawa Microfinance bank" },
  { label: "NAVY MICROFINANCE BANK", value: "NAVY MICROFINANCE BANK" },
  { label: "NDDC MICROFINANCE BANK", value: "NDDC MICROFINANCE BANK" },
  { label: "Ndiorah MFB", value: "Ndiorah MFB" },
  { label: "NEPTUNE MICROFINANCE BANK", value: "NEPTUNE MICROFINANCE BANK" },
  { label: "NET MFB", value: "NET MFB" },
  { label: "NEWDAWN MICROFINANCE BANK", value: "NEWDAWN MICROFINANCE BANK" },
  { label: "NEW GOLDEN PASTURES MICROFINANCE BANK", value: "NEW GOLDEN PASTURES MICROFINANCE BANK" },
  { label: "New Prudent Mort", value: "New Prudent Mort" },
  { label: "NEXIM BANK", value: "NEXIM BANK" },
  { label: "NICE  MICROFINANCE  BANK", value: "NICE  MICROFINANCE  BANK" },
  { label: "Nigeria PrisonsMicrofinance bank", value: "Nigeria PrisonsMicrofinance bank" },
  { label: "NIP Virtual Bank", value: "NIP Virtual Bank" },
  { label: "NIRSAL NATIONAL MICROFINANCE BANK", value: "NIRSAL NATIONAL MICROFINANCE BANK" },
  { label: "NOVA MB", value: "NOVA MB" },
  { label: "NPF MICROFINANCE BANK", value: "NPF MICROFINANCE BANK" },
  { label: "NSEHE MICROFINANCE BANK", value: "NSEHE MICROFINANCE BANK" },
  { label: "NSUK MICROFINANCE BANK", value: "NSUK MICROFINANCE BANK" },
  { label: "NUGGETS MFB", value: "NUGGETS MFB" },
  { label: "NUMO MICROFINANCE BANK", value: "NUMO MICROFINANCE BANK" },
  { label: "NUTURE MFB", value: "NUTURE MFB" },
  { label: "Nwannegadi MFB", value: "Nwannegadi MFB" },
  { label: "OAKLAND MICROFINACE BANK", value: "OAKLAND MICROFINACE BANK" },
  { label: "OAU MICROFINANCE BANK LTD", value: "OAU MICROFINANCE BANK LTD" },
  { label: "Oche MFB", value: "Oche MFB" },
  { label: "OCTOPUS MICROFINANCE BANK LTD", value: "OCTOPUS MICROFINANCE BANK LTD" },
  { label: "ODOAKPU MICROFINANCE BANK LIMITED", value: "ODOAKPU MICROFINANCE BANK LIMITED" },
  { label: "OHAFIA MFB", value: "OHAFIA MFB" },
  { label: "OHHA MICROFINANCE BANK", value: "OHHA MICROFINANCE BANK" },
  { label: "OJOKORO MICROFINANCE BANK", value: "OJOKORO MICROFINANCE BANK" },
  { label: "Oke-Aro Oredegbe Microfinance Bank", value: "Oke-Aro Oredegbe Microfinance Bank" },
  { label: "OKENGWE MICROFINANCE BANK", value: "OKENGWE MICROFINANCE BANK" },
  { label: "OK MICROFINANCE BANK", value: "OK MICROFINANCE BANK" },
  { label: "Okpoga MFB", value: "Okpoga MFB" },
  { label: "Okuku Microfinance Bank", value: "Okuku Microfinance Bank" },
  { label: "OLABISI ONABANJO UNIVERSITY MICROFINANCE BANK", value: "OLABISI ONABANJO UNIVERSITY MICROFINANCE BANK" },
  { label: "OLIVE MFB", value: "OLIVE MFB" },
  { label: "Olowolagba Microfinance Bank", value: "Olowolagba Microfinance Bank" },
  { label: "Oluchukwu MFB", value: "Oluchukwu MFB" },
  { label: "OMIYE MFB", value: "OMIYE MFB" },
  { label: "OPAY", value: "OPAY" },
  { label: "OPTIMUS BANK", value: "OPTIMUS BANK" },
  { label: "ORAUKWU MICROFINANCE BANK", value: "ORAUKWU MICROFINANCE BANK" },
  { label: "Orisun MFB", value: "Orisun MFB" },
  { label: "ORITABASORUN MICROFINANCE BANK", value: "ORITABASORUN MICROFINANCE BANK" },
  { label: "Oscotech MFB", value: "Oscotech MFB" },
  { label: "OSPOLY MICROFINANCE BANK", value: "OSPOLY MICROFINANCE BANK" },
  { label: "OTECH MICROFINANCE BANK LTD", value: "OTECH MICROFINANCE BANK LTD" },
  { label: "Otuo Microfinance Bank", value: "Otuo Microfinance Bank" },
  { label: "OYAN MICROFINANCE BANK", value: "OYAN MICROFINANCE BANK" },
  { label: "PAGA", value: "PAGA" },
  { label: "Page Financials", value: "Page Financials" },
  { label: "PALMCOAST  MICROFINANCE BANK", value: "PALMCOAST  MICROFINANCE BANK" },
  { label: "PALMPAY", value: "PALMPAY" },
  { label: "Parallex Bank", value: "Parallex Bank" },
  { label: "PARKWAY-READYCASH", value: "PARKWAY-READYCASH" },
  { label: "PARRALEX", value: "PARRALEX" },
  { label: "PATHFINDER MFB", value: "PATHFINDER MFB" },
  { label: "PATRICK GOLD", value: "PATRICK GOLD" },
  { label: "PayAttitude Online", value: "PayAttitude Online" },
  { label: "PAYSTACK-TITAN", value: "PAYSTACK-TITAN" },
  { label: "Peace Microfinance Bank", value: "Peace Microfinance Bank" },
  { label: "Pecan Trust Microfinance Bank", value: "Pecan Trust Microfinance Bank" },
  { label: "PENNYWISE MICROFINANCE BANK", value: "PENNYWISE MICROFINANCE BANK" },
  { label: "PERSONAL TRUST MICROFINANCE BANK", value: "PERSONAL TRUST MICROFINANCE BANK" },
  { label: "PETRA MICROFINANCE BANK", value: "PETRA MICROFINANCE BANK" },
  { label: "PFI FINANCE COMPANY LIMITED", value: "PFI FINANCE COMPANY LIMITED" },
  { label: "PILLAR MFB", value: "PILLAR MFB" },
  { label: "PLATINUM MORTGAGE BANK", value: "PLATINUM MORTGAGE BANK" },
  { label: "POLARIS BANK", value: "POLARIS BANK" },
  { label: "POLYBADAN MICROFINANCE BANK", value: "POLYBADAN MICROFINANCE BANK" },
  { label: "POLYUWANNA MFB", value: "POLYUWANNA MFB" },
  { label: "Preeminent Microfinance Bank", value: "Preeminent Microfinance Bank" },
  { label: "PremiumTrust Bank", value: "PremiumTrust Bank" },
  { label: "PRESTIGE MICROFINANCE BANK", value: "PRESTIGE MICROFINANCE BANK" },
  { label: "PRISCO MICROFINANCE BANK", value: "PRISCO MICROFINANCE BANK" },
  { label: "PRISTINE DIVITIS MICROFINANCE BANK", value: "PRISTINE DIVITIS MICROFINANCE BANK" },
  { label: "PROJECTS MICROFINANCE BANK", value: "PROJECTS MICROFINANCE BANK" },
  { label: "PROSPECTS MFB", value: "PROSPECTS MFB" },
  { label: "PROSPERITY MICROFINANCE BANK", value: "PROSPERITY MICROFINANCE BANK" },
  { label: "PROVIDUS BANK", value: "PROVIDUS BANK" },
  { label: "Prudent MFB", value: "Prudent MFB" },
  { label: "PURPLEMONEY MFB", value: "PURPLEMONEY MFB" },
  { label: "PYRAMID MICROFINANCE BANK", value: "PYRAMID MICROFINANCE BANK" },
  { label: "QUBE MICROFINANCE BANK LTD", value: "QUBE MICROFINANCE BANK LTD" },
  { label: "QUICKFUND MICROFINANCE BANK", value: "QUICKFUND MICROFINANCE BANK" },
  { label: "RAHAMA MFB", value: "RAHAMA MFB" },
  { label: "RANDALPHA MICROFINANCE BANK", value: "RANDALPHA MICROFINANCE BANK" },
  { label: "RAND MERCHANT BANK", value: "RAND MERCHANT BANK" },
  { label: "RAYYAN MFB", value: "RAYYAN MFB" },
  { label: "Refuge Mortgage Bank", value: "Refuge Mortgage Bank" },
  { label: "REGENT MFB", value: "REGENT MFB" },
  { label: "REHOBOTH MICROFINANCE BANK", value: "REHOBOTH MICROFINANCE BANK" },
  { label: "RELIANCE MFB", value: "RELIANCE MFB" },
  { label: "RENMONEY MICROFINANCE BANK", value: "RENMONEY MICROFINANCE BANK" },
  { label: "REPHIDIM MICROFINANCE BANK", value: "REPHIDIM MICROFINANCE BANK" },
  { label: "Resident Fintech Limited", value: "Resident Fintech Limited" },
  { label: "REVELATION MICROFINANCE BANK", value: "REVELATION MICROFINANCE BANK" },
  { label: "RICHWAY MFB", value: "RICHWAY MFB" },
  { label: "RIGO MICROFINANCE BANK", value: "RIGO MICROFINANCE BANK" },
  { label: "RIMA MICROFINANCE BANK", value: "RIMA MICROFINANCE BANK" },
  { label: "ROCKSHIELD MICROFINANCE BANK", value: "ROCKSHIELD MICROFINANCE BANK" },
  { label: "Royal Blue MFB", value: "Royal Blue MFB" },
  { label: "ROYAL EXCHANGE MICROFINANCE BANK", value: "ROYAL EXCHANGE MICROFINANCE BANK" },
  { label: "RSU MICROFINANCE BANK", value: "RSU MICROFINANCE BANK" },
  { label: "Rubies MFB", value: "Rubies MFB" },
  { label: "SAFEGATE MICROFINANCE BANK", value: "SAFEGATE MICROFINANCE BANK" },
  { label: "Safe Haven MFB", value: "Safe Haven MFB" },
  { label: "SafeTrust Mortgage", value: "SafeTrust Mortgage" },
  { label: "SAGAMU MICROFINANCE BANK", value: "SAGAMU MICROFINANCE BANK" },
  { label: "SAGE GREY FINANCE LIMITED", value: "SAGE GREY FINANCE LIMITED" },
  { label: "SEAP Microfinance Bank", value: "SEAP Microfinance Bank" },
  { label: "Seed Capital Microfinance Bank", value: "Seed Capital Microfinance Bank" },
  { label: "SEEDVEST MICROFINANCE BANK", value: "SEEDVEST MICROFINANCE BANK" },
  { label: "SHALOM MICROFINANCE BANK", value: "SHALOM MICROFINANCE BANK" },
{ label: "Shepherd Trust Microfinance Bank", value: "Shepherd Trust Microfinance Bank" },
  { label: "SHIELD MICROFINANCE BANK", value: "SHIELD MICROFINANCE BANK" },
  { label: "Shongom Microfinance Bank", value: "Shongom Microfinance Bank" },
  { label: "Signature Bank", value: "Signature Bank" },
  { label: "SIMPLE FINANCE LIMITED", value: "SIMPLE FINANCE LIMITED" },
  { label: "SMARTCASH PAYMENT SERVICE BANK", value: "SMARTCASH PAYMENT SERVICE BANK" },
  { label: "SNOW MFB", value: "SNOW MFB" },
  { label: "SOLID ALLIANZE MICROFINANCE BANK", value: "SOLID ALLIANZE MICROFINANCE BANK" },
  { label: "SOLIDROCK MICROFINANCE BANK", value: "SOLIDROCK MICROFINANCE BANK" },
  { label: "SOURCE MICROFINANCE BANK", value: "SOURCE MICROFINANCE BANK" },
  { label: "Sparkle", value: "Sparkle" },
  { label: "SPECTRUM MICROFINANCE BANK", value: "SPECTRUM MICROFINANCE BANK" },
  { label: "STANBICIBTC BANK", value: "STANBICIBTC BANK" },
  { label: "STANBIC IBTC @EASE WALLET", value: "STANBIC IBTC @EASE WALLET" },
  { label: "STANDARDCHARTERED", value: "STANDARDCHARTERED" },
  { label: "Standard Microfinance Bank", value: "Standard Microfinance Bank" },
  { label: "Stanford MFB", value: "Stanford MFB" },
  { label: "STATESIDE MFB", value: "STATESIDE MFB" },
  { label: "STB MORTGAGE BANK", value: "STB MORTGAGE BANK" },
  { label: "Stellas Microfinance bank", value: "Stellas Microfinance bank" },
  { label: "STERLING BANK", value: "STERLING BANK" },
  { label: "STOCKCORP MICROFINANCE BANK", value: "STOCKCORP MICROFINANCE BANK" },
  { label: "Sulsap MFB", value: "Sulsap MFB" },
  { label: "Sunbeam Microfinance Bank", value: "Sunbeam Microfinance Bank" },
  { label: "SUNTRUST BANK", value: "SUNTRUST BANK" },
  { label: "SUPPORT MICROFINANCE BANK", value: "SUPPORT MICROFINANCE BANK" },
  { label: "SUPREME MICROFINANCE BANK", value: "SUPREME MICROFINANCE BANK" },
  { label: "TagPay", value: "TagPay" },
  { label: "TAJ BANK", value: "TAJ BANK" },
  { label: "TAJ_PINSPAY", value: "TAJ_PINSPAY" },
  { label: "TANGALE MICROFINANCE BANK", value: "TANGALE MICROFINANCE BANK" },
  { label: "TANGERINE MONEY", value: "TANGERINE MONEY" },
  { label: "TASUED MICROFINANCE BANK LTD", value: "TASUED MICROFINANCE BANK LTD" },
  { label: "TEASYMOBILE", value: "TEASYMOBILE" },
  { label: "Tekla Finance Ltd", value: "Tekla Finance Ltd" },
  { label: "TF MICROFINANCE BANK", value: "TF MICROFINANCE BANK" },
  { label: "THRIVE MFB", value: "THRIVE MFB" },
  { label: "TITAN TRUST BANK", value: "TITAN TRUST BANK" },
  { label: "Total Trust Microfinance Bank", value: "Total Trust Microfinance Bank" },
  { label: "TREASURES MICROFINANCE BANK", value: "TREASURES MICROFINANCE BANK" },
  { label: "TRIDENT MICROFINANCE BANK", value: "TRIDENT MICROFINANCE BANK" },
  { label: "TRINITY FINANCIAL SERVICES LIMITED", value: "TRINITY FINANCIAL SERVICES LIMITED" },
  { label: "Triple A Microfinance bank", value: "Triple A Microfinance bank" },
  { label: "TRIVES FINANCE COMPANY LTD", value: "TRIVES FINANCE COMPANY LTD" },
  { label: "TRUSTBANC J6 MICROFINANCE BANK LIMITED", value: "TRUSTBANC J6 MICROFINANCE BANK LIMITED" },
  { label: "Trustbond", value: "Trustbond" },
  { label: "TRUSTFUND MICROFINANCE BANK", value: "TRUSTFUND MICROFINANCE BANK" },
  { label: "TRUST MFB", value: "TRUST MFB" },
  { label: "U AND C MFB", value: "U AND C MFB" },
  { label: "UDA MICROFINANCE BANK", value: "UDA MICROFINANCE BANK" },
  { label: "UHURU MICROFINANCE BANK", value: "UHURU MICROFINANCE BANK" },
  { label: "Ummah Microfinance Bank", value: "Ummah Microfinance Bank" },
  { label: "UMUCHINEMERE PROCREDIT MFB", value: "UMUCHINEMERE PROCREDIT MFB" },
  { label: "UMUCHUKWU MICROFINANCE BANK", value: "UMUCHUKWU MICROFINANCE BANK" },
  { label: "Umunnachi Microfinance Bank", value: "Umunnachi Microfinance Bank" },
  { label: "UNAAB MFB", value: "UNAAB MFB" },
  { label: "UNIBADAN MICROFINANCE BANK", value: "UNIBADAN MICROFINANCE BANK" },
  { label: "UNIBEN MICROFINANCE BANK", value: "UNIBEN MICROFINANCE BANK" },
  { label: "Unical MFB", value: "Unical MFB" },
  { label: "UNIFUND MICROFINANCE BANK LIMITED", value: "UNIFUND MICROFINANCE BANK LIMITED" },
  { label: "UNILAG MICROFINANCE BANK", value: "UNILAG MICROFINANCE BANK" },
  { label: "UNILORIN MICROFINANCE BANK", value: "UNILORIN MICROFINANCE BANK" },
  { label: "UNION BANK", value: "UNION BANK" },
  { label: "UNITED BANK FOR AFRICA", value: "UNITED BANK FOR AFRICA" },
  { label: "UNITY BANK", value: "UNITY BANK" },
  { label: "UNIUYO MICROFINANCE BANK", value: "UNIUYO MICROFINANCE BANK" },
  { label: "UNN MFB", value: "UNN MFB" },
  { label: "Ure MFB", value: "Ure MFB" },
  { label: "UZONDU MICROFINANCE BANK LIMITED", value: "UZONDU MICROFINANCE BANK LIMITED" },
  { label: "VALE FINANCE LIMITED", value: "VALE FINANCE LIMITED" },
  { label: "Verdant Microfinance Bank", value: "Verdant Microfinance Bank" },
  { label: "VFD MFB", value: "VFD MFB" },
  { label: "VIRTUE MFB", value: "VIRTUE MFB" },
  { label: "VISA MICROFINANCE BANK", value: "VISA MICROFINANCE BANK" },
  { label: "VTNetworks", value: "VTNetworks" },
  { label: "WAYA MICROFINANCE BANK", value: "WAYA MICROFINANCE BANK" },
  { label: "WAYA MICROFINANCE BANK LTD", value: "WAYA MICROFINANCE BANK LTD" },
  { label: "WEMA BANK", value: "WEMA BANK" },
  { label: "WESLEY MFB", value: "WESLEY MFB" },
  { label: "WETLAND MFB", value: "WETLAND MFB" },
  { label: "WinView Bank", value: "WinView Bank" },
  { label: "WRA MFB", value: "WRA MFB" },
  { label: "WUDIL MICROFINANCE BANK", value: "WUDIL MICROFINANCE BANK" },
  { label: "Xpress Wallet", value: "Xpress Wallet" },
  { label: "XSLNCE Microfinance Bank", value: "XSLNCE Microfinance Bank" },
  { label: "YCT MICROFINANCE BANK", value: "YCT MICROFINANCE BANK" },
  { label: "YES MFB", value: "YES MFB" },
  { label: "Yobe MFB", value: "Yobe MFB" },
  { label: "ZENITH BANK PLC", value: "ZENITH BANK PLC" },
  { label: "ZenithMobile", value: "ZenithMobile" },
  { label: "ZIKORA MICROFINANCE BANK", value: "ZIKORA MICROFINANCE BANK" },
  { label: "ZWallet", value: "ZWallet" }
];